Logging:
  LogLevel:
    Default: Information
    Microsoft: Information
    Microsoft.Hosting.Lifetime: Information

ConnectionStrings:
  FinanceDatabase: "Host=localhost;Port=60339;User=dboFinance;Password=mdn9VBYldGcmLo01lt5Y3lpQqeE=;Database=dboFinance;SslMode=None"

IntegrationsConfig:
  PayFast:
    MerchantId: 12345678
    MerchantKey: "abcdefghijklmnop"
    Passphrase: "zyxwvutsrqponmlkjihgfedcba"
    JsonApiBaseUrl: "https://api.payfast.co.za/v1"
    FormApiBaseUrl: "https://www.payfast.co.za"
    ReturnUrl: "https://google.com"
    CancelUrl: "https://google.com"
    NotifyUrl: "/v1/TransactionResource/Settlement/{transactionId}"

Hazelcast:
  ServerAddress: "localhost:5701"

TransactionConfig:
  AllowedSettlementStatuses:
    - "Pending"
    - "Authorised"

ForexConfig:
  BaseCurrency: "ZAR"
  ExchangeRatesApiUrl: "https://latest.currency-api.pages.dev/v1/currencies"
