-- Migration script: V20250603124748_createCallbackEventsSequenceWithTable.sql
-- Author: markmngoma
-- Created on: 03/06/2025 12:47

CREATE SEQUENCE IF NOT EXISTS dboFinance.TRANSACTION_DETAILS_SEQ START WITH 1 INCREMENT BY 1 CACHE 1 NOCYCLE;

CREATE TABLE IF NOT EXISTS dboFinance.TRANSACTION_DETAILS (
   ID BIGINT UNSIGNED NOT NULL DEFAULT NEXTVAL(dboFinance.TRANSACTION_DETAILS_SEQ),
   EVENT_TYPE VARCHAR(100) NOT NULL,
   SOURCE VARCHAR(50) NOT NULL DEFAULT 'PAY_FAST',
   PAYLOAD VARCHAR(255) NOT NULL,
   STATUS ENUM('RECEIVED', 'PROCESSED', 'FAILED', 'IGNORED') NOT NULL DEFAULT 'RECEIVED',
   TRANSACTION_ID BIGINT UNSIGNED DEFAULT NULL,
   RECEIVED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PROCESSED_AT DATETIME DEFAULT NULL,
   ERROR_MESSAGE TEXT DEFAULT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (TRANSACTION_ID) REFERENCES dboFinance.TRANSACTIONS(ID)
);
