-- Migration script: V20250603123844_createFinancialProductSequenceWithTable.sql
-- Author: markmngoma
-- Created on: 03/06/2025 12:38
CREATE SEQUENCE IF NOT EXISTS dboFinance.FINANCIAL_PRODUCT_SEQ START WITH 1 INCREMENT BY 1 CACHE 1 NOCYCLE;

CREATE TABLE IF NOT EXISTS dboFinance.FINANCIAL_PRODUCT (
   ID BIGINT UNSIGNED NOT NULL DEFAULT NEXTVAL(dboFinance.FINANCIAL_PRODUCT_SEQ),
   NAME VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(150) NOT NULL,
   PRICE DECIMAL(10, 2) NOT NULL,
   BILLING_CYCLE TINYINT NOT NULL DEFAULT 3,
   CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
);
