-- Migration script: V20250603124114_createSubscriptionSequenceWithTable.sql
-- Author: markmngoma
-- Created on: 03/06/2025 12:41
CREATE SEQUENCE IF NOT EXISTS dboFinance.SUBSCRIPTIONS_SEQ START WITH 1 INCREMENT BY 1 CACHE 1 NOCYCLE;

CREATE TABLE IF NOT EXISTS dboFinance.SUBSCRIPTIONS (
   ID BIGINT UNSIGNED NOT NULL DEFAULT NEXTVAL(dboFinance.SUBSCRIPTIONS_SEQ),
   BUSINESS_ID BIGINT UNSIGNED NOT NULL,
   FINANCIAL_PRODUCT_ID BIGINT UNSIGNED NOT NULL,
   STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
   START_DATE DATE NOT NULL,
   END_DATE DATE DEFAULT NULL,
   CANCELLED_AT DATETIME DEFAULT NULL,
   CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   FOREIGN KEY (FINANCIAL_PRODUCT_ID) REFERENCES dboFinance.FINANCIAL_PRODUCT(ID)
);
